# baseURL = "https://marcleroy.github.io/ecrandeveille"
baseURL = "http://localhost:1313/ecrandeveille"
languageCode = "en-us"
title = "Techno watch site"
# theme = "dspg"
# theme = "hugo-coder"
# theme = "ananke"
theme = "mainroad"

# themesDir = "../.."
# resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[Author] # Used in authorbox
  name = "Marc Leroy"
  bio = "Marc Leroy's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
  # avatar = "img/avatar.png"

[Params]
  subtitle = "" # Deprecated in favor of .Site.Params.logo.subtitle
  description = "Marc Leroy's dev blog about .Net" # Site description. Used in meta description
  copyright = "Marc Leroy" # Footer copyright holder, otherwise will use site title
  opengraph = true # Enable OpenGraph if true
  schema = true # Enable Schema
  twitter_cards = true # Enable Twitter Cards if true
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show authorbox at bottom of pages if true
  toc = true # Enable Table of Contents
  pager = true # Show pager navigation (prev/next links) at the bottom of pages if true
  post_meta = ["author", "date", "categories", "translations"] # Order of post meta information
  mainSections = ["posts", "blog", "news"] # Specify section pages to show on home page and the "Recent articles" widget
  # dateformat = "2006-01-02" # Change the format of dates
  # mathjax = true # Enable MathJax
  # mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # Specify MathJax path
  # mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # Specify MathJax config
  # googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Load Google Fonts
  # highlightColor = "" # Deprecated in favor of .Site.Params.style.vars.highlightColor
  # customCSS = ["css/custom.css"] # Include custom CSS files
  # customJS = ["js/custom.js"] # Include custom JS files



[Params.style.vars]
  # highlightColor = "#e22d30" # Override highlight color
  highlightColor = "#8e52cb" # Override highlight color

  # Override font-family sets. Secondary font-family set responsible for pre, code, kbd, and samp tags font
  # Take care of different quotes OR escaping symbols in these params if necessary
  fontFamilyPrimary = "'Open Sans', Helvetica, Arial, sans-serif"
  fontFamilySecondary = "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace"

[Params.logo]
  image = "images/vslogo.png" # Logo image. Path relative to "static"
  title = "Techno watch site" # Logo title, otherwise will use site title
  subtitle = "trying to follow .Net evolution" # Logo subtitle

[Params.sidebar]
  home = "right" # Configure layout for home page
  list = "left"  # Configure layout for list pages
  single = false # Configure layout for single pages
  # Enable widgets in given order
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
  # alternatively "ddg-search" can be used, to search via DuckDuckGo
  # widgets = ["ddg-search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[languages]
  [languages.en]
    title = "Tech watch site"
    weight = 1
    contentDir = "content"
  [languages.fr]
    title = "Ecran de veille"
    weight = 2
    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# [params]
#   favicon = ""
#   site_logo = ""
#   description = "The last theme you'll ever need. Maybe."
#   facebook = ""
#   twitter = "https://twitter.com/GoHugoIO"
#   instagram = ""
#   youtube = ""
#   github = ""
#   gitlab = ""
#   linkedin = ""
#   mastodon = ""
#   slack = ""
#   stackoverflow = ""
#   rss = ""
#   # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
#   background_color_class = "bg-black"
#   featured_image = "/images/vuesemnoz.jpg"
#   recent_posts_number = 2
